import { describe, expect, test } from "bun:test";
import manifest from "../../packs/islamic-network-alafasy-128-v1.manifest.json";
import data from "../../packs/islamic-network-alafasy-128-v1.data.json";
import { getSurah } from "../../src/data/quran.ts";
import { STARTER_RECITATION_PACK } from "../../src/features/resources/public-recitation.ts";

describe("public starter recitation pack", () => {
  test("covers all canonical ayat with documented HTTPS CDN URLs", () => {
    const expected: { verse_key: string; audio_url: string }[] = [];
    let globalAyah = 0;
    for (let surahId = 1; surahId <= 114; surahId++) {
      const surah = getSurah(surahId)!;
      for (const verse of surah.verses) {
        globalAyah += 1;
        expected.push({
          verse_key: `${surahId}:${verse.id}`,
          audio_url: `https://cdn.islamic.network/quran/audio/128/ar.alafasy/${globalAyah}.mp3`,
        });
      }
    }
    expect(data.recitations).toEqual(expected);
  });

  test("manifest pins the exact generated bytes and checksum", async () => {
    const path = new URL("../../packs/islamic-network-alafasy-128-v1.data.json", import.meta.url);
    const file = Bun.file(path);
    const bytes = await file.arrayBuffer();
    expect(bytes.byteLength).toBe(manifest.content.bytes);
    expect(new Bun.CryptoHasher("sha256").update(bytes).digest("hex")).toBe(manifest.content.sha256);
    expect(await file.text()).toBe(`${JSON.stringify({ recitations: data.recitations })}\n`);
  });

  test("runtime trust anchors match the checked release assets", async () => {
    const manifestPath = new URL("../../packs/islamic-network-alafasy-128-v1.manifest.json", import.meta.url);
    const manifestBytes = await Bun.file(manifestPath).arrayBuffer();
    expect(new Bun.CryptoHasher("sha256").update(manifestBytes).digest("hex")).toBe(STARTER_RECITATION_PACK.manifestSha256);
    expect(manifest.id).toBe(STARTER_RECITATION_PACK.id);
    expect(manifest.version).toBe(STARTER_RECITATION_PACK.version);
    expect(manifest.kind).toBe(STARTER_RECITATION_PACK.kind);
    expect(manifest.source.provider).toBe(STARTER_RECITATION_PACK.provider);
    expect(manifest.source.url).toBe(STARTER_RECITATION_PACK.sourceUrl);
    expect(manifest.content.bytes).toBe(STARTER_RECITATION_PACK.downloadBytes);
    expect(manifest.content.sha256).toBe(STARTER_RECITATION_PACK.dataSha256);
  });
});
